# Generated by Django 4.1 on 2022-11-23 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualtask',
            name='task',
        ),
    ]
