# Generated by Django 4.1 on 2022-11-23 12:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_task'),
        ('tasks', '0002_remove_individualtask_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualtask',
            name='bonus',
            field=models.PositiveIntegerField(default=100, verbose_name='Бонус за выполнение задания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='individualtask',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='Категория участника'),
        ),
        migrations.AlterField(
            model_name='individualtask',
            name='karathon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.karathon', verbose_name='Карафон'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='individualtask',
            name='multiple_number',
            field=models.PositiveIntegerField(blank=True, default=5, null=True, verbose_name='Кол-во шагов, кратное этому числу (N)'),
        ),
        migrations.AlterField(
            model_name='individualtask',
            name='steps',
            field=models.PositiveIntegerField(blank=True, default=10000, null=True, verbose_name='Количество шагов в задании (S)'),
        ),
        migrations.AlterField(
            model_name='individualtask',
            name='task_date_report',
            field=models.DateField(blank=True, default=datetime.date(2022, 11, 22), null=True, verbose_name='День с какого берем шаги (D)'),
        ),
    ]
