# Generated by Django 4.1 on 2022-11-24 07:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_individualtask_bonus_alter_individualtask_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualtask',
            name='task_date_report',
            field=models.DateField(blank=True, default=datetime.date(2022, 11, 23), null=True, verbose_name='День с какого берем шаги (D)'),
        ),
        migrations.CreateModel(
            name='IndividualTaskParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнено?')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.individualtask', verbose_name='Задание')),
            ],
        ),
    ]
