# Generated by Django 4.1 on 2023-03-22 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_individualtask_task_date_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualtask',
            name='task_date_report',
            field=models.DateField(blank=True, default=datetime.date(2023, 3, 21), null=True, verbose_name='День с какого берем шаги (D)'),
        ),
    ]
