# Generated by Django 4.1 on 2023-04-24 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_individualtask_task_date_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualtask',
            name='task_date_report',
            field=models.DateField(blank=True, default=datetime.date(2023, 4, 23), null=True, verbose_name='День с какого берем шаги (D)'),
        ),
    ]
