# Generated by Django 4.0.10 on 2023-11-28 09:46

import apps.core.validators
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_karathon_is_presentation_and_more'),
        ('tasks', '0013_alter_individualtask_task_date_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(validators=[apps.core.validators.not_earlier_today], verbose_name='Дата')),
                ('type', models.CharField(choices=[('walk_steps', 'Пройти S шагов'), ('double_best', 'Удвоить лучший результат или S шагов'), ('double_result_day', 'Удвоить результат дня D или S шагов'), ('improve_best', 'Улучшить лучший результат или S шагов'), ('improve_result_day', 'Улучшить результат дня D или S шагов'), ('add_steps_to_day', 'Добавить S шагов ко дню D'), ('palindrome', 'Зеркалка'), ('steps_of_consecutive_digits', 'Число шагов из последовательных цифр'), ('steps_multiple_number', 'Число шагов, кратное N'), ('add_steps_to_report_digit', 'Добавить X-тысяч шагов, где X - цифра в отчёте дня D, занимающая позицию P'), ('best_personal_record', 'Побить личный рекорд или S шагов')], max_length=100, verbose_name='Тип')),
                ('steps', models.PositiveIntegerField(blank=True, default=10000, null=True, verbose_name='Количество шагов в задании (S)')),
                ('task_date_report', models.DateField(blank=True, default=datetime.date(2023, 11, 27), null=True, verbose_name='День с какого берем шаги (D)')),
                ('multiple_number', models.PositiveIntegerField(blank=True, default=5, null=True, verbose_name='Кол-во шагов, кратное этому числу (N)')),
                ('position', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Позиция цифры в отчёте (P)')),
                ('addition', models.CharField(blank=True, max_length=200, null=True, verbose_name='Дополнение к заданию')),
                ('bonus', models.PositiveIntegerField(verbose_name='Бонус за выполнение задания')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='Категория участника')),
                ('karathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.karathon', verbose_name='Карафон')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.DeleteModel(
            name='IndividualTask',
        ),
    ]
