# Generated by Django 4.0.10 on 2023-11-29 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_task_delete_individualtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_date_report',
            field=models.DateField(blank=True, default=datetime.date(2023, 11, 28), null=True, verbose_name='День с какого берем шаги (D)'),
        ),
    ]
