# Generated by Django 4.0.10 on 2023-12-06 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_task_task_date_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_date_report',
            field=models.DateField(blank=True, default=datetime.date(2023, 12, 5), null=True, verbose_name='День с какого берем шаги (D)'),
        ),
    ]
