# Generated by Django 4.0.10 on 2023-12-14 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alter_task_task_date_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_date_report',
            field=models.DateField(blank=True, default=datetime.date(2023, 12, 13), null=True, verbose_name='День с какого берем шаги (D)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('walk_steps', 'Пройти S шагов'), ('double_best', 'Удвоить лучший результат или S шагов'), ('double_result_day', 'Удвоить результат дня D или S шагов'), ('improve_best', 'Улучшить лучший результат или S шагов'), ('improve_result_day', 'Улучшить результат дня D или S шагов'), ('add_steps_to_day', 'Добавить S шагов ко дню D'), ('palindrome', 'Зеркалка, но не менее S шагов'), ('steps_of_consecutive_digits', 'Число шагов из последовательных цифр'), ('steps_multiple_number', 'Число шагов, кратное N, но не менее S шагов'), ('add_steps_to_report_digit', 'Добавить X-тысяч шагов, где X - цифра в отчёте дня D, занимающая позицию P'), ('best_personal_record', 'Побить личный рекорд или S шагов')], max_length=100, verbose_name='Тип'),
        ),
    ]
