# Generated by Django 4.1 on 2022-10-19 12:56

import apps.core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('steps', models.PositiveIntegerField(verbose_name='Количество шагов')),
                ('photo', models.ImageField(upload_to=apps.core.utils.get_report_image_path, verbose_name='Фотоподтверждение')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Шаг',
                'verbose_name_plural': 'Шагов',
            },
        ),
    ]
