# Generated by Django 4.1 on 2022-11-14 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('steps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'verbose_name': 'Шаг', 'verbose_name_plural': 'Шаги'},
        ),
        migrations.AlterField(
            model_name='step',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to=settings.AUTH_USER_MODEL, verbose_name='Участник'),
        ),
    ]
