# Generated by Django 4.1 on 2022-11-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0002_alter_step_options_alter_step_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='is_completion_task',
            field=models.BooleanField(default=0, verbose_name='Задание выполнено?'),
            preserve_default=False,
        ),
    ]
