# Generated by Django 4.1 on 2022-11-23 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0003_step_is_completion_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='is_completion_task',
        ),
    ]
