# Generated by Django 4.1 on 2022-11-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0004_remove_step_is_completion_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='bonus',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Дополнительный бонус'),
        ),
        migrations.AddField(
            model_name='step',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Задание дня выполнено?'),
        ),
    ]
