# Generated by Django 4.0.10 on 2023-10-31 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0005_step_bonus_step_is_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ('-date',), 'verbose_name': 'Шаг', 'verbose_name_plural': 'Шаги'},
        ),
    ]
