# Generated by Django 4.0.10 on 2023-11-13 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_karathon_is_presentation_and_more'),
        ('steps', '0006_alter_step_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='karathon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.karathon', verbose_name='Карафон'),
            preserve_default=False,
        ),
    ]
