# Generated by Django 4.1 on 2022-10-19 12:56

import apps.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Karathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Номер карафона')),
                ('starts_at', models.DateField(validators=[apps.core.validators.not_earlier_today], verbose_name='Дата начала')),
                ('finished_at', models.DateField(validators=[apps.core.validators.not_earlier_today], verbose_name='Дата окончания')),
                ('type', models.CharField(choices=[('individual', 'Индивидуальный'), ('team', 'Командный')], max_length=10, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Карафон',
                'verbose_name_plural': 'Карафоны',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(validators=[apps.core.validators.not_earlier_today], verbose_name='Дата')),
                ('task', models.CharField(max_length=200, verbose_name='Задание')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
                ('karathon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.karathon')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
    ]
