# Generated by Django 4.1 on 2022-11-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task_addition_alter_task_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название категории благотворительности')),
            ],
            options={
                'verbose_name': 'Категория благотворительности',
                'verbose_name_plural': 'Категории благотворительности',
            },
        ),
    ]
