# Generated by Django 4.1 on 2022-11-23 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_charitycategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
