# Generated by Django 4.0.10 on 2023-11-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='karathon',
            name='is_presentation',
            field=models.BooleanField(default=False, verbose_name='Отображать видеопрезентацию'),
        ),
        migrations.AddField(
            model_name='karathon',
            name='video_presentation_link',
            field=models.CharField(blank=True, help_text='Введите ссылку на видеопрезентацию на youtube, если она есть, в формате "https://www.youtube.com/embed/XxXxXxX"', max_length=70, null=True, verbose_name='Ссылка на видеопрезентацию на youtube'),
        ),
    ]
