# Generated by Django 4.0.10 on 2023-12-26 08:59

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_karathon_is_presentation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRecordsmans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя рекордсмена')),
                ('photo', models.ImageField(blank=True, upload_to=apps.core.utils.get_participant_photo_path, verbose_name='Фото рекордсмена')),
                ('steps', models.PositiveIntegerField(verbose_name='Количество шагов')),
                ('karathon_number', models.PositiveIntegerField(verbose_name='Номер карафона')),
            ],
            options={
                'verbose_name': 'Добавленный рекордсмен',
                'verbose_name_plural': 'Добавленные рекордсмены',
            },
        ),
    ]
