# Generated by Django 4.1 on 2022-11-14 08:59

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_participant_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='photo',
            field=models.ImageField(blank=True, upload_to=apps.core.utils.get_participant_photo_path, verbose_name='Аватарка'),
        ),
    ]
