# Generated by Django 4.1 on 2022-11-15 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_charitycategory'),
        ('account', '0004_alter_participant_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinnerQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(max_length=10, verbose_name='Почтовый индекс')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Населенный пункт')),
                ('address', models.CharField(max_length=200, verbose_name='Населенный пункт')),
                ('shirt_size', models.CharField(choices=[('xxs', 'xxs'), ('xs', 'xs'), ('s', 's'), ('m', 'm'), ('l', 'l'), ('xl', 'xl'), ('xxl', 'xxl'), ('3xl', '3xl'), ('4xl', '4xl')], default='Europe/Moscow', max_length=5)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
                ('сharity_сategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.charitycategory', verbose_name='Категория благотворительности')),
            ],
        ),
    ]
