# Generated by Django 4.1 on 2022-11-15 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_charitycategory'),
        ('account', '0005_winnerquestionnaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('karathon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.karathon', verbose_name='Карафон')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
            ],
        ),
    ]
