# Generated by Django 4.1 on 2023-01-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_winner_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='timezone_offset',
            field=models.CharField(choices=[('+3', 'Мск'), ('+4', 'Мск+01'), ('+5', 'Мск+02'), ('+6', 'Мск+03'), ('+7', 'Мск+04'), ('+8', 'Мск+05'), ('+9', 'Мск+06'), ('+10', 'Мск+07'), ('+11', 'Мск+08'), ('+12', 'Мск+09'), ('+2', 'Мск-01'), ('+1', 'Мск-02'), ('0', 'Мск-03'), ('-1', 'Мск-04'), ('-2', 'Мск-05'), ('-3', 'Мск-06'), ('-4', 'Мск-07'), ('-5', 'Мск-08'), ('-6', 'Мск-09'), ('-7', 'Мск-10'), ('-8', 'Мск-11'), ('-9', 'Мск-12'), ('-10', 'Мск-13'), ('-11', 'Мск-14')], default='+3', max_length=3),
        ),
    ]
