# Generated by Django 4.0.10 on 2023-11-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_participant_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='winnerquestionnaire',
            options={'verbose_name': 'Победитель', 'verbose_name_plural': 'Победители'},
        ),
        migrations.AlterField(
            model_name='winnerquestionnaire',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Населенный пункт'),
        ),
        migrations.AlterField(
            model_name='winnerquestionnaire',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Населенный пункт'),
        ),
        migrations.AlterField(
            model_name='winnerquestionnaire',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='winnerquestionnaire',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='winnerquestionnaire',
            name='shirt_size',
            field=models.CharField(choices=[('xxs', 'xxs'), ('xs', 'xs'), ('s', 's'), ('m', 'm'), ('l', 'l'), ('xl', 'xl'), ('xxl', 'xxl'), ('3xl', '3xl'), ('4xl', '4xl')], default='l', max_length=5, verbose_name='размер футболки'),
        ),
    ]
