# Generated by Django 4.0.10 on 2023-11-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_winnerquestionnaire_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winnerquestionnaire',
            old_name='сharity_сategory',
            new_name='charity_category',
        ),
        migrations.AlterField(
            model_name='winnerquestionnaire',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес'),
        ),
    ]
