# Generated by Django 4.0.10 on 2023-11-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_remove_winnerquestionnaire_participant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='winnerquestionnaire',
            name='is_displayed',
            field=models.BooleanField(default=False, verbose_name='Форма отображается'),
        ),
    ]
