# Generated by Django 4.0.10 on 2023-12-06 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_winnerquestionnaire_is_displayed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='winnerquestionnaire',
            name='winner',
        ),
        migrations.AddField(
            model_name='winnerquestionnaire',
            name='participant',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Участник'),
            preserve_default=False,
        ),
    ]
