# Generated by Django 4.0.10 on 2023-12-14 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_karathon_is_presentation_and_more'),
        ('account', '0015_remove_participant_timezone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='karathon',
        ),
        migrations.CreateModel(
            name='ParticipantsKarathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Участник участвует в карафоне')),
                ('karathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.karathon', verbose_name='Карафон')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Участник карафонов',
                'verbose_name_plural': 'Участники карафонов',
            },
        ),
    ]
