# Generated by Django 4.0.10 on 2023-12-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_remove_participant_karathon_participantskarathon'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='telegram',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Ник в Telegram'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='instagram',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Ник в Instagram'),
        ),
    ]
