# Generated by Django 4.1 on 2022-10-28 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_teamparticipant_options_desiredteam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desiredteam',
            old_name='desired_list',
            new_name='desired_participant',
        ),
    ]
