# Generated by Django 4.1 on 2022-10-28 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_rename_desired_list_desiredteam_desired_participant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DesiredTeam',
        ),
    ]
