# Generated by Django 4.1 on 2022-10-28 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0004_delete_desiredteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesiredTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desired_team', to=settings.AUTH_USER_MODEL)),
                ('participant_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_team', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Желаемый сокомандник',
                'verbose_name_plural': 'Желаемые сокомандники',
            },
        ),
    ]
