# Generated by Django 4.1 on 2022-10-28 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0005_desiredteam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desiredteam',
            name='participant_team',
        ),
        migrations.AddField(
            model_name='desiredteam',
            name='wisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wisher', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
