# Generated by Django 4.1 on 2022-10-31 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0007_remove_desiredteam_wisher_desiredteam_desirer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desiredteam',
            name='desired_team',
        ),
        migrations.AddField(
            model_name='desiredteam',
            name='desired_participant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='desired_participant', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
