# Generated by Django 4.1 on 2022-11-14 08:59

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_remove_desiredteam_desired_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintDesiredTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Желаемые сокомандники',
            },
            managers=[
                ('desired_team_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='desiredteam',
            options={},
        ),
    ]
