# Generated by Django 4.1 on 2023-03-22 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_rename_datetime_notification_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('is_viewed', '-date')},
        ),
    ]
