# Generated by Django 4.1 on 2023-04-24 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_notification_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='step',
        ),
    ]
