# Generated by Django 4.0.10 on 2023-12-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='header',
            field=models.CharField(max_length=150, verbose_name='Вставка в заголовок'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.CharField(max_length=300, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='header',
            field=models.CharField(max_length=150, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='text',
            field=models.CharField(max_length=300, verbose_name='Текст'),
        ),
    ]
